#!/usr/bin/python3

#
# Add, remove, modify the layers to sync, here. The tool doesn't change the bblayers.conf so be sure to update that too
#

remotes = [
    {"name": "yocto",        "url": "git://git.yoctoproject.org"},
    {"name": "openembedded", "url": "git://git.openembedded.org"},
    {"name": "github",       "url": "https://github.com"},
    {"name": "github-ssh",   "url": "ssh://git@github.com"},
    {"name": "phytec-ssh",   "url": "ssh://git@git.phytec.de"},
    {"name": "phytec-git",   "url": "git://git.phytec.de"},
    {"name": "phytec-github", "url": "ssh://git@github.com/phytec"},
]

layers = [
    {"rev":"refs/tags/BSP-Yocto-Ampliphy-AM62x-PD23.2.1", "branch":"kirkstone",  "repo":"meta-phytec",                    "path":"meta-phytec",             "remote":"phytec-git"},
    {"rev":"refs/tags/BSP-Yocto-Ampliphy-AM62x-PD23.2.1", "branch":"kirkstone",  "repo":"meta-ampliphy",                  "path":"meta-ampliphy",           "remote":"phytec-git"},
    {"rev":"ed3b8e3559b83ee5071f4bc11f00361b3c279117",  "branch":"kirkstone",  "repo":"phytec/meta-summit-radio",         "path":"meta-summit-radio",       "remote":"github"},
    {"rev":"b6f6c729453cb88961488e3332046517e2fe99bb",  "branch":"kirkstone",  "repo":"poky",                             "path":"poky",                    "remote":"yocto"},
    {"rev":"8bb16533532b6abc2eded7d9961ab2a108fd7a5b",  "branch":"kirkstone",  "repo":"meta-openembedded",                "path":"meta-openembedded",       "remote":"openembedded"},
    {"rev":"ed6dc67ffb143a4c4fac01e0b7e8a60fc6260b85",  "branch":"kirkstone",  "repo":"rauc/meta-rauc",                   "path":"meta-rauc",               "remote":"github"},
    {"rev":"d7b7b6fb6c7c5545e718e44f38853d1718ce5446",  "branch":"kirkstone",  "repo":"meta-arm",                         "path":"meta-arm",                "remote":"yocto"},
    {"rev":"refs/tags/09.02.00.009",                    "branch":"kirkstone",  "repo":"meta-ti",                          "path":"meta-ti",                 "remote":"yocto"},
    {"rev":"06c240c3c235fa06fe724e278d53463ac67cc26b",  "branch":"kirkstone",  "repo":"meta-security",                    "path":"meta-security",           "remote":"yocto"},
    {"rev":"5f386fa561d23b777f467064a1d973cbf66c68ac",  "branch":"kirkstone",  "repo":"meta-phyverso-evcs",               "path":"meta-phyverso-evcs",      "remote":"phytec-github"},
    {"rev":"dfc364b932a783ddb294e6a6cc562ce38b4bfaff",  "branch":"kirkstone",  "repo":"meta-lumissil-greenphy",           "path":"meta-lumissil-greenphy",       "remote":"phytec-github"},
    {"rev":"1.0-rc2",  "branch":"kirkstone-release/1.0",  "repo":"PionixPro/meta-basecamp",          "path":"meta-basecamp",      "remote":"github-ssh"},
]

#
# Please don't change the code locally or if you do please talk with the others to integrate your changes 
#
import os
import sys
import argparse
import subprocess


layers_location="../source/"

# ANSI color codes
RED = '\033[91m'
YELLOW = '\033[93m'
RESET = '\033[0m'

def print_error(message):
    print(f"\033[97;41mError:\033[0m {message}")

def print_warning(message):
    print(f"\033[30;43mWarning:\033[0m {message}")

def print_msg(message):
    print(f"\033[97;42mExecute:\033[0m {message}")

def format_underline(message):
    return f"\033[34;4m{message}\033[0m"

def get_remote_url(remote_name):
    for remote in remotes:
        if remote["name"] == remote_name:
            return remote["url"]
    return None

def loop_over_layers(do_init, do_sync, sync_method):
    for layer in layers:
        print()
        path = f'{layers_location}{layer["path"]}'
        if os.path.exists(path) and os.listdir(path):
            if do_init:
                url = get_remote_url(layer["remote"])+ "/" + layer["repo"]
                print_warning(f'Init was requested for repo {format_underline(url)} using existing path {path}')
                print_warning("Existing folder (layer) will not be altered, run the tool again with --sync to update it. You can delete it (if you don't have changes) and rerun with --init if needed.")
                continue
            if not layer["rev"]:
                command = f'cd {path} && git {sync_method} && git checkout {layer["branch"]}'
            else:
                command = f'cd {path} && git {sync_method} && git checkout {layer["rev"]}'
        else:
            if do_sync:
                print_warning(f"Sync was requested but the folder {path} doesn't exist, we will do nothing, run init to create it")
                continue
            if not layer["rev"]:
                command = f'git clone -b {layer["branch"]} --single-branch {get_remote_url(layer["remote"])}/{layer["repo"]} {path}'
            else:
                command = f'git clone -b {layer["branch"]} --single-branch {get_remote_url(layer["remote"])}/{layer["repo"]} {path} && cd {path} && git checkout {layer["rev"]}'
        print_msg(command)
        process = subprocess.Popen(command, shell=True)
        exit_code = process.wait()
        if exit_code != 0:
            print_error(f"The last command returned with error ({exit_code}), exiting ...")
            sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description='Creates the layer structure and synchronizes it')
    parser.add_argument('--init', action='store_true', help='Initializes the entire Yocto structure')
    parser.add_argument('--sync', action='store_true', help='Synchronizes the layers to the given revision or to the given branch HEAD')
    parser.add_argument('--sync_method', choices=['fetch', 'pull'], help='Synchronization method')

    # Parse command-line arguments
    args = parser.parse_args()

    # Validate args
    if not args.init and not args.sync:
        print_error("You need to provide an operation, either --init or --sync\n")
        parser.print_help()
        sys.exit(1)
    if args.init and args.sync_method:
        print_error("Cannot use --init with --sync_method\n")
        parser.print_help()
        sys.exit(1)

    if args.init:
        print_msg("Add hooks so that if the setup is changed after a pull request or a commit, it will be executed automatically and sync the repos")
        process = subprocess.Popen("cp .githooks/* .git/hooks/", shell=True)
        exit_code = process.wait()
        if exit_code != 0:
            print_error(f"I can't install the hooks, git the error code ({exit_code}), please be warned that setup will not be executed automatically when it changes.")
            sys.exit(1)
        process = subprocess.Popen("chmod +x .git/hooks/post-*", shell=True)
        exit_code = process.wait()
        if exit_code != 0:
            print_error(f"I can't make the hooks executable, got error code ({exit_code}), please be warned that setup will not be executed automatically when it changes.")
            sys.exit(1)

    # Set the working directory to the script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    loop_over_layers(args.init, args.sync, "fetch" if not args.sync_method else args.sync_method)

if __name__ == "__main__":
    main()

