settings:
  telemetry_enabled: false
active_modules:
  api:
    connections:
      evse_manager:
      - implementation_id: evse
        module_id: evse_manager_1_ac
      - implementation_id: evse
        module_id: evse_manager_2_dc
    module: API
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      selection_algorithm: PlugEvents
    connections:
      token_provider:
      - module_id: token_provider_1_ac
        implementation_id: main
      - module_id: token_provider_2_dc
        implementation_id: main
      token_validator:
      - module_id: token_validator
        implementation_id: main
      evse_manager:
      - module_id: evse_manager_1_ac
        implementation_id: evse
      - module_id: evse_manager_2_dc
        implementation_id: evse
  energy_manager:
    connections:
      energy_trunk:
      - implementation_id: energy_grid
        module_id: grid_connection_point
    module: EnergyManager
#
# AC Charger on Port 1
#
  evse_manager_1_ac:
    config_module:
      ac_enforce_hlc: true
      ac_hlc_enabled: true
      ac_hlc_use_5percent: true
      ac_nominal_voltage: 230
      charge_mode: AC
      evse_id: DE*PNX*E1234567*1
      payment_enable_contract: false
      payment_enable_eim: true
      session_logging: true
      session_logging_path: /tmp/logs
      connector_id: 1
    connections:
      bsp:
      - implementation_id: connector_1
        module_id: phyverso_mcu
      hlc:
      - implementation_id: charger
        module_id: iso_1_ac
      slac:
      - implementation_id: main
        module_id: slac_1_ac
      connector_lock:
      - implementation_id: connector_lock_1
        module_id: phyverso_mcu
    module: EvseManager
    telemetry:
      id: 1
  iso_1_ac:
    config_module:
      device: seth0
    connections:
      security:
      - implementation_id: main
        module_id: evse_security
    module: EvseV2G
  slac_1_ac:
    config_implementation:
      main:
        device: seth0
        number_of_sounds: 10
        link_status_detection: true
    connections: {}
    module: EvseSlac
#
# DC Charger on Port 2
#
  evse_manager_2_dc:
    config_module:
      charge_mode: DC
      evse_id: DE*PNX*E1234567*2
      payment_enable_contract: false
      payment_enable_eim: true
      session_logging: true
      session_logging_path: /tmp/logs
      connector_id: 2
    connections:
      bsp:
      - implementation_id: connector_2
        module_id: phyverso_mcu
      hlc:
      - implementation_id: charger
        module_id: iso_2_dc
      slac:
      - implementation_id: main
        module_id: slac_2_dc
      powersupply_DC:
        - module_id: powersupply_2_dc
          implementation_id: main
      imd:
        - module_id: imd_2_dc
          implementation_id: main
    module: EvseManager
    telemetry:
      id: 2
  powersupply_2_dc:
    config_module:
      can_device: main_mcan0
    module: InfyPower_BEG1K075G
  imd_2_dc:
    module: IMDSimulator
  iso_2_dc:
    config_module:
      device: seth1
    connections:
      security:
      - implementation_id: main
        module_id: evse_security
    module: EvseV2G
  slac_2_dc:
    config_implementation:
      main:
        device: seth1
        number_of_sounds: 10
        link_status_detection: true
    connections: {}
    module: EvseSlac
#
#
#
  grid_connection_point:
    config_module:
      fuse_limit_A: 100
      phase_count: 3
    connections:
      energy_consumer:
      - implementation_id: energy_grid
        module_id: evse_manager_1_ac
      - implementation_id: energy_grid
        module_id: evse_manager_2_dc
    module: EnergyNode
  evse_security:
    module: EvseSecurity
  persistent_store:
    module: PersistentStore
    config_module:
      sqlite_db_file_path: /etc/everest/everest_persistent_store.db
    connections: {}
  setup:
    config_module:
      localization: true
      setup_simulation: false
      setup_wifi: true
    connections:
      store:
      - module_id: persistent_store
        implementation_id: main
    module: Setup
  token_provider_1_ac:
    config_implementation:
      main:
        timeout: 120
        token: DEADBEEF
        type: RFID
        connector_id: 1
    connections:
      evse:
      - implementation_id: evse
        module_id: evse_manager_1_ac
    module: DummyTokenProvider
  token_provider_2_dc:
    config_implementation:
      main:
        timeout: 120
        token: DEADBEEF
        type: RFID
        connector_id: 2
    connections:
      evse:
      - implementation_id: evse
        module_id: evse_manager_2_dc
    module: DummyTokenProvider
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: DummyTokenValidator
  phyverso_mcu:          
    module: PhyVersoBSP
    config_module:
      conn1_max_current_A_import: 16
      conn1_dc: false
      conn2_max_current_A_import: 80
      conn2_dc: true
      reset_gpio_bank: 2
      conn1_motor_lock_type: 1
      conn2_motor_lock_type: 1
      serial_port: /dev/ttyS6

