# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-phyverso-basecamp"
BBFILE_PATTERN_meta-phyverso-basecamp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-phyverso-basecamp = "99"

LAYERDEPENDS_meta-phyverso-basecamp = "core"
LAYERSERIES_COMPAT_meta-phyverso-basecamp = "kirkstone"
