# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-phyverso-everest"
BBFILE_PATTERN_meta-phyverso-everest = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-phyverso-everest = "99"

LAYERDEPENDS_meta-phyverso-everest = "core"
LAYERSERIES_COMPAT_meta-phyverso-everest = "scarthgap"

PHYVERSO_USE_VIRTUALIZATION ??= "1"
PHYVERSO_USE_DISPLAY_APP ??= "1"
PHYVERSO_BUILD_WIC ??= "1"
PHYVERSO_SYSFS_USER_GPIOS ??= "0"

GIT_REPOSITORY_URL ??= "git://git@github.com/PionixPro"
PREFIX_GIT_REPOSITORY ??= ""

# overwrite meta-lumissil-greenphy definition -> newer poky has 1.6.5
PREFERRED_VERSION_libgpiod = "1.6.5"